@startuml

interface Conducible {
     +conducir() 
}
interface Transportador { 
    +cargarMercancia()
}

class Coche implements Conducible
class Camion implements Conducible, Transportador

Conducible <|.. Camion
Transportador <|.. Camion

@enduml
